### ISSUE TITLE
Return type `any` in type declaration files of distributed package

### ISSUE THREAD

**Issue by toto6038** [harlan-zw/nuxt-site-config#10]
## Description
In the distributed package of release v1.6.6, some function signatures have `any` return type. 

## Details
For source `@/packages/module/src/runtime/composables/utils.ts`
https://github.com/harlan-zw/nuxt-site-config/blob/b57f7ddb92d666fab82393dcb0aa6d4bb5a8834a/packages/module/src/runtime/composables/utils.ts#L28-L41

In Visual Studio Code, as the inlay hint shows that it's possible to infer the implicit return type. I have confirmed that TypeScript version used in the editor is 5.2.2 that is consistent with the dependency.
<img width="1191" alt="image" src="https://github.com/harlan-zw/nuxt-site-config/assets/50100922/8149e1a3-088f-40a8-9966-e6189503f021">

But in the generated type declaration `@/packages/module/dist/runtime/composables/utils.d.ts`
<img width="854" alt="SCR-20231205-kayc" src="https://github.com/harlan-zw/nuxt-site-config/assets/50100922/b0bf2c7f-f25f-41df-89df-bc8dab56569c">

The return type becomes `any`.

I'm not sure whether the problem is caused by @unjs/mkdist which is used by @nuxt/module-builder under the hood to generate type declaration files.

## Solution
Mark return type explicitly.

Modified source
<img width="1191" alt="image" src="https://github.com/harlan-zw/nuxt-site-config/assets/50100922/e6370976-5145-4c49-ab77-0778cf732b3f">

Generated type declaration
<img width="856" alt="image" src="https://github.com/harlan-zw/nuxt-site-config/assets/50100922/a3cc6050-148f-4f84-bd25-63b6a0e8e8e2">

### System / Nuxt Info

```Shell
- Operating System: `Darwin`
- Node Version:     `v18.18.2`
- Nuxt Version:     `3.8.2`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.0`
- Package Manager:  `pnpm@8.10.2`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

**Comment by harlan-zw** [comment]
Thank you for this issue @toto6038 

I've added explicit return types for all of these functions, hopefully, this resolves it for you (available in v1.6.7).

Let me know if you still have issues though.
