### ISSUE TITLE
Deprecate SiteLink (Discussion)

### ISSUE THREAD

**Issue by harlan-zw** [harlan-zw/nuxt-site-config#19]
### Details

The `<SiteLink>` component was introduced as a way for end-users and modules to implement links that respected the trailing slash option.

However, in the latest Nuxt SEO, we now set the default trailing slash for the NuxtLink, this is a recent feature of the Nuxt core (see https://github.com/harlan-zw/nuxt-seo/commit/1879310).

So the only valid usage of SiteLink would now just to be add links that are absolute (which isn't recommended generally) and links with a custom base, which seems quite niche. 

Therefore we likely don't need SiteLink anymore and it will be deprecated unless anyone has any good ideas for it to exist.

**Comment by MuhammadM1998** [comment]
Related to applying the trailing slash to the NuxtLink. Does this mean that any NuxtLink wrapper (e.g. `NuxtLinkLocale` from nuxt/i18n) will inherit the same settings and I don't have to add trailing slashed manually?

**Comment by harlan-zw** [comment]
Yes this looks to be the case but haven't tested it personally.

**Comment by MuhammadM1998** [comment]
I'll check it out and report to i18n repo if there's issues. I think with that in hand `SiteLink` should be deprecated indeed

**Comment by harlan-zw** [comment]
This is blocked by https://github.com/nuxt/nuxt/issues/25532.

Basically default trailing slash rule in Nuxt is currently blocking
