### ISSUE TITLE
Using `useSiteConfig` inside a server route fail

### ISSUE THREAD

**Issue by Barbapapazes** [harlan-zw/nuxt-site-config#2]
### Describe the bug

Hello,

I'm trying to use the composable `useSiteConfig` inside a server route and I got this error.

![image](https://github.com/harlan-zw/nuxt-site-config/assets/45267552/15a3467b-be59-4720-b962-4f09a8f01921)

### System / Nuxt Info

```Shell
------------------------------
- Operating System: Linux
- Node Version:     v18.16.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.12
- Builder:          vite
- User Config:      app, modules, css, nitro, content, unocss, site, sitemap, devtools
- Runtime Modules:  @nuxt/content@2.7.2, @vueuse/nuxt@10.3.0, @unocss/nuxt@0.54.3, nuxt-simple-robots@3.1.0, nuxt-simple-sitemap@3.1.5, @nuxthq/studio@0.13.4
- Build Modules:    -
------------------------------
```

**Comment by harlan-zw** [comment]
Can you provide the code you're using and in what context exactly?

In Nuxt server code the usage should be the same, but in Nitro code you need to pass the H3Event in as the first argument.

**Comment by Barbapapazes** [comment]
Will check, thx
