### ISSUE TITLE
fix: `package.json`'s description takes precendence over `i18n`'s description

### ISSUE THREAD

**Issue by dargmuesli** [harlan-zw/nuxt-site-config#26]
### Describe the bug

It seems like `package.json`'s description takes precendence over `i18n`'s description. I have some `description` field in a `package.json` and `locales/[de|en].json` (two files) containing

```json
{
  "nuxtSiteConfig": {
    "description": "..."
  }
}
```

I'd expect the locale files' descriptions to take precedence but I see the `package.json` locales' descriptions being preferred instead.

### Reproduction

Can add one if necessary.

**Comment by dargmuesli** [comment]
Removing the `package.json`'s description let's the head meta tags `description` and `og:description` disappear. It seems the `i18n` descriptions are not loaded at the time those meta tags are created?

I can use `useServerSeoMeta({description: siteConfig.description})` as a workaround though. `i18n` is loaded when using `const siteConfig = useSiteConfig()`.

**Comment by harlan-zw** [comment]
Can you provide some more context on how you're using it? If you're accessing the site config within a plugin you'll need to run it after the site config i18n plugin.

```ts
export default defineNuxtPlugin({
  dependsOn: ['nuxt-site-config:i18n'],
  // ...
})
```

**Comment by dargmuesli** [comment]
It seems another dependency update resolved the issue. Thank you!
