### ISSUE TITLE
ques: Are there any plans to add it to `Nuxt Modules`?

### ISSUE THREAD

**Issue by shinGangan** [harlan-zw/nuxt-site-config#30]
### Details

All modules except `site-config` are currently added to [Nuxt modules](https://nuxt.com/modules).

Are there any plans to add this module as well?
If you plan to add it, I will create a PR (I want you to focus on developing SEO etc.)

I am asking this question considering that there is a roadmap such as "We plan to add the necessary features after development is completed."

### ⛓️ Related

harlan-zw/nuxt-seo#229

**Comment by shinGangan** [comment]
Hi @harlan-zw , I would be happy if you could reply when you have a time. 🙏

**Comment by harlan-zw** [comment]
Hey, thanks for the question.

This module is kind of a tricky one, it's _meant_ to only be consumed by modules who want to expose shared site config. I'd consider adding it to Nuxt Modules once Nuxt SEO is stable.

Although end users also need to find it when they need to use the APIs exposed by the module :thinking: I'll definitely consider it but I think it should wait until Nuxt SEO is stable on v2.

**Comment by shinGangan** [comment]
closed issue.

> My doubts have been resolved, thank you.
