### ISSUE TITLE
Install Nuxt Site Config says to use modules.ts without where to put it.

### ISSUE THREAD

**Issue by sosensible** [harlan-zw/nuxt-site-config#31]
### Details

I installed the libraries, but the instructions on this page say to use `modules.ts,` but they don't say where to place the file. The goal is to use NuxtSEO as it was designed. Nothing non-standard.

- [ ] Should it be another name?
- [ ] Should it be in the modules folder?

**Comment by harlan-zw** [comment]
Hi @sosensible,

If you're using the `@nuxtjs/seo` module then it will auto-install all of the modules for you.

The Nuxt Site Config module is specifically for module authors to install alongside their modules, you shouldn't ever need to install this yourself.
