### ISSUE TITLE
warning when setting env `NUXT_SITE_URL` as `NUXT_APP_BASE_URL` with origin

### ISSUE THREAD

**Issue by n0099** [harlan-zw/nuxt-site-config#32]
### Describe the bug

```bash
git clone https://github.com/n0099/open-tbm && cd open-tbm
git checkout 7a7775c3cb7ab18c033673765f0fb1789f5ad1f4
cat <<'EOF' > .env
NUXT_APP_BASE_URL=/tbm
NUXT_SITE_URL=https://n0099.net/tbm
EOF
yarn && yarn dev
```
```
 WARN  [Nuxt Site Config] Invalid config provided, please correct:
  - url "https://n0099.net/tbm" from buildEnv should not contain a path
```

### Reproduction

https://github.com/n0099/open-tbm/tree/7a7775c3cb7ab18c033673765f0fb1789f5ad1f4

### System / Nuxt Info

- Operating System: Linux
- Node Version:     v22.7.0
- Nuxt Version:     3.13.0
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  yarn@4.4.1
- Builder:          -
- User Config:      compatibilityDate, devServer, devtools, srcDir, imports, modules, pinia, eslint, vueQuery, site, sitemap, ogImage, schemaOrg, features, sourcemap, build, vite, experimental, runtimeConfig
- Runtime Modules:  @nuxt/eslint@0.5.4, @pinia/nuxt@0.5.4, @vueuse/nuxt@11.0.3, @ant-design-vue/nuxt@1.4.2, @hebilicious/vue-query-nuxt@0.3.0, @vesp/nuxt-fontawesome@1.1.0, @nuxtjs/seo@2.0.0-rc.19
- Build Modules:    -

**Comment by harlan-zw** [comment]
Hi, so you should avoid including the path on the site url, it should be the canonical origin. This module will respect whatever you choose as the `NUXT_APP_BASE_URL` and make sure it's prepended to any URL generated.

```
cat <<'EOF' > .env
NUXT_APP_BASE_URL=/tbm
NUXT_SITE_URL=n0099.net
EOF
```

If you're having issues with this config please let me know.

**Comment by n0099** [comment]
With
```env
NUXT_APP_BASE_URL=/tbm
NUXT_SITE_URL=https://n0099.net
```
`useSiteConfig().url` will only return `https://n0099.net` without the nuxt base url `/tbm`

**Comment by n0099** [comment]
> Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
