### ISSUE TITLE
Probleme import on Sitelin component.

### ISSUE THREAD

**Issue by DascoRM** [harlan-zw/nuxt-site-config#9]
### Describe the bug
Hello, 
I've a probleme import on Sitelink component...
Just after install nuxt-simple-sitemap v4.0.1
![error](https://github.com/harlan-zw/nuxt-site-config/assets/105069605/92a4b838-ecad-44cf-b67d-e654fd75ecd9)
You know why this erorr pop ?

### Reproduction

after install nuxt-sitemap

### System / Nuxt Info

```Shell
Nuxt v3.8.0
```

**Comment by harlan-zw** [comment]
Hi, did you disable auto imports by any chance?

**Comment by DascoRM** [comment]
No, we have a simple Nuxt3 typescript setup, by the book. The issue appeared after installing the nuxt-simple-sitemap module which has this repository as a dependancy.

**Comment by harlan-zw** [comment]
Did you run `nuxi prepare` first? `#imports` is definitely valid but is generated at runtime

However, you should probably not lint node_modules

**Comment by MaxNvk** [comment]
Have the same problem as well... Simple Nuxt 3 + TypeScript setup. I run `nuxi prepare`, but it doesn't help.

**Comment by harlan-zw** [comment]
I've reworked the logic in 1.6.1 which should solve the type issue.
